### ISSUE TITLE
reddit_tft - beam.FlatMap - invalid syntax

### ISSUE THREAD

**Issue by andrewm4894** [GoogleCloudPlatform/cloudml-samples#151]
For problems running the sample code please provide the following information.

*Running on Google Cloud instance n1-highmem-8 (8 vCPUs, 52 GB memory)
*Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-112-generic x86_64)

$ pip freeze |grep tensorflow
tensorflow==1.3.0
tensorflow-tensorboard==0.1.7

### Describe the problem

When i try run the preprocess.py part of the reddit_tft tutorial i get below error:

```
andrew_maguire@data-science-box:~/cloudml-samples-master/reddit_tft$ python preprocess.py --training_data fh-bigquery.reddit_comments.2015_12 \
>                      --eval_data fh-bigquery.reddit_comments.2016_01 \
>                      --predict_data fh-bigquery.reddit_comments.2016_02 \
>                      --output_dir "${PREPROCESS_OUTPUT}" \
>                      --project_id "${PROJECT}" \
>                      --cloud
  File "preprocess.py", line 118
    | 'DropRandom' >> beam.FlatMap(lambda (k, vs): vs))
                                          ^
SyntaxError: invalid syntax
```

Looks like maybe a beam issue with the overloaded operators maybe. 

If i do
```
pip freeze |grep apache-beam
```
I get nothing

If i try install beam directly with
```
pip install apache-beam
```
i get:

```
Collecting apache-beam
  Using cached apache-beam-2.2.0.zip
    Complete output from command python setup.py egg_info:
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        For performance reasons, doesn't actually impose an ordering
        on unequal values (always returning 1).
        """
        if type(left) is not type(right):
          return cmp(type(left), type(right))
                   ^
    ------------------------------------------------------------
    
    apache_beam/utils/windowed_value.py:83:16: undeclared name not builtin: cmp
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-e4p79c0x/apache-beam/setup.py", line 173, in <module>
        'apache_beam/utils/windowed_value.py',
      File "/home/andrew_maguire/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 934, in cythonize
        cythonize_one(*args)
      File "/home/andrew_maguire/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1056, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: apache_beam/utils/windowed_value.py
    Compiling apache_beam/coders/stream.pyx because it changed.
    Compiling apache_beam/runners/worker/statesampler.pyx because it changed.
    Compiling apache_beam/coders/coder_impl.py because it changed.
    Compiling apache_beam/metrics/execution.py because it changed.
    Compiling apache_beam/runners/common.py because it changed.
    Compiling apache_beam/runners/worker/logger.py because it changed.
    Compiling apache_beam/runners/worker/opcounters.py because it changed.
    Compiling apache_beam/runners/worker/operations.py because it changed.
    Compiling apache_beam/transforms/cy_combiners.py because it changed.
    Compiling apache_beam/utils/counters.py because it changed.
    Compiling apache_beam/utils/windowed_value.py because it changed.
    [ 1/11] Cythonizing apache_beam/coders/coder_impl.py
    [ 2/11] Cythonizing apache_beam/coders/stream.pyx
    [ 3/11] Cythonizing apache_beam/metrics/execution.py
    [ 4/11] Cythonizing apache_beam/runners/common.py
    [ 5/11] Cythonizing apache_beam/runners/worker/logger.py
    [ 6/11] Cythonizing apache_beam/runners/worker/opcounters.py
    [ 7/11] Cythonizing apache_beam/runners/worker/operations.py
    [ 8/11] Cythonizing apache_beam/runners/worker/statesampler.pyx
    [ 9/11] Cythonizing apache_beam/transforms/cy_combiners.py
    [10/11] Cythonizing apache_beam/utils/counters.py
    [11/11] Cythonizing apache_beam/utils/windowed_value.py
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-e4p79c0x/apache-beam/
```

Looking here: https://stackoverflow.com/questions/46532385/command-python-setup-py-egg-info-failed-with-error-code-1-installing-apache

I see maybe i'm trying to run the tutorial using python 3. 

Maybe some sort of virtualenv set up for the tutorial might be useful.

**Comment by andrewm4894** [comment]
Sorry - my bad if i run `python2 preprocess.py ...` its all good. 

Just wanted to raise the issue in case anyone else comes across it while assuming its all python3
