### ISSUE TITLE
Wrong return in generate_input_fn in Trainer Package Template

### ISSUE THREAD

**Issue by FriedNails** [GoogleCloudPlatform/cloudml-samples#187]
In `input.py`  `generate_input_fn` function's description says that it returns a function:
https://github.com/GoogleCloudPlatform/cloudml-samples/blob/472d363968cee20a42bbed05c049d8291b499d4f/cloudml-template/template/trainer/input.py#L186

but it actually calls that function in return statement: 
https://github.com/GoogleCloudPlatform/cloudml-samples/blob/472d363968cee20a42bbed05c049d8291b499d4f/cloudml-template/template/trainer/input.py#L242

and it causes the following error:
```
Traceback (most recent call last): 
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name) 
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals 
File "/root/.local/lib/python2.7/site-packages/trainer/task.py", line 389, in <module> main() 
File "/root/.local/lib/python2.7/site-packages/trainer/task.py", line 374, in main run_experiment(run_config) 
File "/root/.local/lib/python2.7/site-packages/trainer/task.py", line 283, in run_experiment max_steps=int(train_steps)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 147, in __new__ _validate_input_fn(input_fn) 
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 51, in _validate_input_fn 
    raise TypeError('`input_fn` must be callable, given: {}'.format(input_fn))
```

Brackets removal fixes the error

**Comment by happyhuman** [comment]
Thank you for reporting this issue. I am working on fixing it.

**Comment by happyhuman** [comment]
The issue is fixed. Thanks again for reporting it.
