### ISSUE TITLE
Keras example will not run with Tensorflow 1.2

### ISSUE THREAD

**Issue by nwandabridges** [GoogleCloudPlatform/cloudml-samples#210]
For problems running the sample code please provide the following information.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.13.5
- **TensorFlow version (use command below)**: 1.2.0
- **Python version**:  3.6.5
- **Exact command to reproduce**:
```
python -m trainer.task --train-files $TRAIN_FILE \
                       --eval-files $EVAL_FILE \
                       --job-dir $JOB_DIR \
                       --train-steps $TRAIN_STEPS
```

### Describe the problem
The Keras tutorial will not run with Tensorflow version 1.2.0 (the version required in requirements.txt).

### Logs
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/Users/andrewbridges/Desktop/keras_tutorial/cloudml-samples/census/keras/trainer/task.py", line 223, in <module>
>     dispatch(**parse_args.__dict__)
>   File "/Users/andrewbridges/Desktop/keras_tutorial/cloudml-samples/census/keras/trainer/task.py", line 93, in dispatch
>     census_model = model.model_fn(INPUT_SIZE, CLASS_SIZE)
>   File "/Users/andrewbridges/Desktop/keras_tutorial/cloudml-samples/census/keras/trainer/model.py", line 73, in model_fn
>     model.add(layers.Dense(labels_dim, activation=softmax))
>   File "/Users/andrewbridges/environments/keras_tutorial/lib/python3.6/site-packages/keras/engine/sequential.py", line 187, in add
>     output_tensor = layer(self.outputs[0])
>   File "/Users/andrewbridges/environments/keras_tutorial/lib/python3.6/site-packages/keras/engine/base_layer.py", line 460, in __call__
>     output = self.call(inputs, **kwargs)
>   File "/Users/andrewbridges/environments/keras_tutorial/lib/python3.6/site-packages/keras/layers/core.py", line 889, in call
>     output = self.activation(output)
>   File "/Users/andrewbridges/environments/keras_tutorial/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3149, in softmax
>     return tf.nn.softmax(x, axis=axis)
> TypeError: softmax() got an unexpected keyword argument 'axis'

**Comment by nwandabridges** [comment]
I've submitted a [pull request](https://github.com/GoogleCloudPlatform/cloudml-samples/pull/212) that resolves this issue.

**Comment by puneith** [comment]
@gogasca can you add keras test in this file https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/census/sample.sh The change should be straightforward (similar to TF). We can merge @nwandabridges PR once we have Keras test.

**Comment by gogasca** [comment]
Sounds good! I will add the example.
