### ISSUE TITLE
Executing Movielens preprocess fails

### ISSUE THREAD

**Issue by lioutasb** [GoogleCloudPlatform/cloudml-samples#217]
### System information
- Linux Ubuntu 16.04
- tensorflow-gpu==1.8.0
- Python 2.7
- tensorflow-transform==0.6.0
- apache-beam==2.4.0

### Describe the problem
I'm trying to execute the [Movielens](https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/movielens) preprocess pipeline locally but it fails.

The command I'm running is the following with the appropriate changes in the paths:

```
LOCAL_TRAINING_INPUT_DIR=/path/to/ml-latest-small/input...
LOCAL_OUTPUT_DIR=/path/to/output
python preprocess.py --input_dir "$LOCAL_TRAINING_INPUT_DIR" \
                     --output_dir "$LOCAL_OUTPUT_DIR" \
                     --percent_eval 20 \
                     --negative_sample_ratio 1 \
                     --negative_sample_label 0.0 \
                     --eval_type ranking \
                     --eval_score_threshold 4.5 \
                     --num_ranking_candidate_movie_ids 1000 \
                     --partition_random_seed 0
```

### Source code / logs
```
Traceback (most recent call last):
  File "preprocess.py", line 491, in <module>
    main()
  File "preprocess.py", line 487, in main
    preprocess(pipeline, args)
  File "preprocess.py", line 402, in preprocess
    | 'Analyze' >> tft.AnalyzeDataset(preprocessing_fn))
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/apache_beam/transforms/ptransform.py", line 820, in __ror__
    return self.transform.__ror__(pvalueish, self.label)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/apache_beam/transforms/ptransform.py", line 488, in __ror__
    result = p.apply(self, pvalueish, label)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/apache_beam/pipeline.py", line 443, in apply
    return self.apply(transform, pvalueish)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/apache_beam/pipeline.py", line 479, in apply
    pvalueish_result = self.runner.apply(transform, pvalueish)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/apache_beam/runners/runner.py", line 174, in apply
    return m(transform, input)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/apache_beam/runners/runner.py", line 180, in apply_PTransform
    return transform.expand(input)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow_transform/beam/impl.py", line 670, in expand
    outputs = self._preprocessing_fn(impl_helper.copy_tensors(inputs))
  File "/home/billiout/test/movielens/preproc/movielens.py", line 263, in preprocessing_fn
    map_to_int, inputs[QUERY_RATED_GENRE_IDS], genre_vocab)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow_transform/api.py", line 161, in apply_function
    return FunctionApplication(fn, args).user_output
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow_transform/api.py", line 89, in __init__
    output = fn(*args)
  File "/home/billiout/test/movielens/preproc/movielens.py", line 259, in map_to_int
    mapping=vocabulary_or_file, num_oov_buckets=1)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/contrib/lookup/lookup_ops.py", line 70, in string_to_index_table_from_tensor
    mapping, num_oov_buckets, default_value, hasher_spec, name=scope)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/contrib/lookup/lookup_ops.py", line 138, in index_table_from_tensor
    name=name)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/lookup_ops.py", line 1099, in index_table_from_tensor
    init, default_value, shared_name=shared_name, name=hash_table_scope)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/lookup_ops.py", line 279, in __init__
    super(HashTable, self).__init__(table_ref, default_value, initializer)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/lookup_ops.py", line 171, in __init__
    self._init = initializer.initialize(self)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/lookup_ops.py", line 350, in initialize
    table.table_ref, self._keys, self._values, name=scope)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/gen_lookup_ops.py", line 386, in initialize_table_v2
    values=values, name=name)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 1 but is rank 0 for 'string_to_index/hash_table/table_init' (op: 'InitializeTableV2') with input shapes: [], [], [1].
```

**Comment by puneith** [comment]
@lioutasb Looks like case of empty input dataset? Can you confirm if things are working for the code sample with the pinned dependencies in requirements.txt?

**Comment by kiminh** [comment]
same issue encoutered. Have you solved this issue @lioutasb ?

**Comment by puneith** [comment]
@kiminh @lioutasb see my comment above, can you confirm?

**Comment by gogasca** [comment]
closing per no response
