### ISSUE TITLE
Error in Preprocessing

### ISSUE THREAD

**Issue by jennings1716** [GoogleCloudPlatform/cloudml-samples#280]
Got Error in running
python trainer/preprocess.py \
>   --input_dict "$DICT_FILE" \
>   --input_path "gs://produce_multi_label_classification/classification_dataset/eval_set.csv" \
>   --output_path "${GCS_PATH}/preproc/eval" \
>   --cloud

Error is 
/usr/local/lib/python2.7/dist-packages/apache_beam/io/gcp/gcsio.py:176: DeprecationWarning: object() takes no parameters
  super(GcsIO, cls).__new__(cls, storage_client))
Traceback (most recent call last):
  File "trainer/preprocess.py", line 490, in <module>
    main(sys.argv[1:])
  File "trainer/preprocess.py", line 486, in main
    run(arg_dict)
  File "trainer/preprocess.py", line 394, in run
    configure_pipeline(p, in_args)
  File "trainer/preprocess.py", line 370, in configure_pipeline
    opt.input_dict, strip_trailing_newlines=True)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/io/textio.py", line 522, in __init__
    skip_header_lines=skip_header_lines)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/io/textio.py", line 117, in __init__
    validate=validate)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/io/filebasedsource.py", line 119, in __init__
    self._validate()
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/options/value_provider.py", line 133, in _f
    return fnc(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/io/filebasedsource.py", line 179, in _validate
    'No files found based on the file pattern %s'

**Comment by puneith** [comment]
@jennings1716 which code are you running?
