### ISSUE TITLE
No module named util error in flowers sample

### ISSUE THREAD

**Issue by slcott** [GoogleCloudPlatform/cloudml-samples#31]
When I try to run the flowers sample I get the following error:

```
Scotts-MBP:flowers slcott$ ./sample.sh 

Using job id:  flowers_slcott_20170331_101454

# Takes about 30 mins to preprocess everything.  We serialize the two
# preprocess.py synchronous calls just for shell scripting ease; you could use
# --runner DataflowRunner to run them asynchronously.  Typically,
# the total worker time is higher when running on Cloud instead of your local
# machine due to increased network traffic and the use of more cost efficient
# CPU's.  Check progress here: https://console.cloud.google.com/dataflow
python trainer/preprocess.py \
  --input_dict "$DICT_FILE" \
  --input_path "gs://cloud-ml-data/img/flower_photos/eval_set.csv" \
  --output_path "${GCS_PATH}/preproc/eval" \
  --cloud
No handlers could be found for logger "oauth2client.contrib.multistore_file"
/usr/local/lib/python2.7/site-packages/apache_beam/coders/typecoders.py:132: UserWarning: Using fallback coder for typehint: Any.
  warnings.warn('Using fallback coder for typehint: %r.' % typehint)
DEPRECATION: pip install --download has been deprecated and will be removed in the future. Pip now has a download command that should be used instead.
Collecting google-cloud-dataflow==0.5.5
  Using cached google-cloud-dataflow-0.5.5.tar.gz
  Saved /var/folders/z2/pb7n1y692j96gj4q1wgwll400000gn/T/tmpqz_elG/google-cloud-dataflow-0.5.5.tar.gz
Successfully downloaded google-cloud-dataflow
Traceback (most recent call last):
  File "trainer/preprocess.py", line 452, in <module>
    main(sys.argv[1:])
  File "trainer/preprocess.py", line 448, in main
    run(arg_dict)
  File "trainer/preprocess.py", line 379, in run
    configure_pipeline(p, in_args)
  File "/usr/local/lib/python2.7/site-packages/apache_beam/pipeline.py", line 170, in __exit__
    self.run().wait_until_finish()
  File "/usr/local/lib/python2.7/site-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 711, in wait_until_finish
    (self.state, getattr(self._runner, 'last_error_msg', None)), self)
apache_beam.runners.dataflow.dataflow_runner.DataflowRuntimeException: Dataflow pipeline failed. State: FAILED, Error:
(8db641b87e775c9): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/batchworker.py", line 666, in run
    self._load_main_session(self.local_staging_directory)
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/batchworker.py", line 411, in _load_main_session
    pickler.load_session(session_file)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/internal/pickler.py", line 230, in load_session
    return dill.load_session(file_path)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 346, in load_session
    module = unpickler.load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 406, in find_class
    return StockUnpickler.find_class(self, module, name)
  File "/usr/lib/python2.7/pickle.py", line 1124, in find_class
    __import__(module)
ImportError: No module named util

Scotts-MBP:flowers slcott$ ls
README.md		pipeline.py		setup.py
__init__.py		requirements.txt	trainer
images_to_json.py	sample.sh
Scotts-MBP:flowers slcott$ cd trainer
Scotts-MBP:trainer slcott$ ls
__init__.py	preprocess.py	util.py
model.py	task.py		util.pyc
Scotts-MBP:trainer slcott$ cd ..
```

Seems to be an issue with apache beam...

**Comment by mikehcheng2** [comment]
This was an issue with util.py not being sent to Dataflow. This is fixed with the most recent push.
