### ISSUE TITLE
[Census] tensorflowcore error in Python 3.5

### ISSUE THREAD

**Issue by gogasca** [GoogleCloudPlatform/cloudml-samples#332]
**Describe the bug**
CMLE running Census sample I get error in Python 3.5

**What sample is this bug related to?**

**Source code / logs**
Census model

**To Reproduce**
Python 3.5

Python script succeeded!
Cleaning up...
```
Running 'tensorflowcore' code sample.
Copying gs://cloud-samples-data/ml-engine/census/data/adult.data.csv...
/ [1 files][  3.8 MiB/  3.8 MiB]                                                
Operation completed over 1 objects/3.8 MiB.                                      
Copying gs://cloud-samples-data/ml-engine/census/data/adult.test.csv...
/ [1 files][  1.9 MiB/  1.9 MiB]                                                
Operation completed over 1 objects/1.9 MiB.                                      
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/src/cloudml-samples/census/tensorflowcore/trainer/task.py", line 35, in <module>
    import trainer.model as model
  File "/usr/local/src/cloudml-samples/census/tensorflowcore/trainer/model.py", line 48, in <module>
    zip(*CATEGORICAL_COLS)[0] + CONTINUOUS_COLS + (LABEL_COLUMN,))
TypeError: 'zip' object is not subscriptable

**Expected behavior**
A clear and concise description of what you expected to happen.

**System Information**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Framework and version (Tensorflow, scikit-learn, XGBoost)**:
- **Python version**:
- **Exact command to reproduce**:
- **Tensorflow Transform environment (if applicable, see below)**:
```

**Additional context**

**Comment by andrewferlitsch** [comment]
Yeah, the line 48 in model.py is semantically wrong. 
UNUSED_COLUMNS = set(CSV_COLUMNS) - set(
    zip(*CATEGORICAL_COLS)[0] + CONTINUOUS_COLS + (LABEL_COLUMN,))

Not sure what coder really meant, but my first guess is they meant to subscript the *CATEGORICAL_COLS and not the zip() of it.

**Comment by andrewferlitsch** [comment]
followup from gogasca:  I will modify the example to work with zip. (In Python 2, zip returned a list. In Python 3, zip returns an iterable object. But you I can make it into a list just by calling list)

**Comment by andrewferlitsch** [comment]
bug wasa fixed 4 months ago. Now closing it.
