### ISSUE TITLE
Unable to run on Nvidia v100

### ISSUE THREAD

**Issue by sreenivasmr** [GoogleCloudPlatform/cloudml-samples#344]
**Describe the bug**
I am running the sample on CMLE by changing the 
    'use_tpu', default=True, 
to
    'use_tpu', default=False,

flags.DEFINE_string(
    'data_format', default='channels_last',
to
flags.DEFINE_string(
    'data_format', default='channels_first',

in resnet_main.py  assuming the code will run successfully on GPUs, with the below config

trainingInput:
  scaleTier: CUSTOM
  masterType: large_model_v100
  workerType: large_model_v100
  parameterServerType: large_model
  workerCount: 1
  parameterServerCount: 3

However the job fails with the below error.
```
The replica ps 0 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/resnet/resnet_main.py", line 501, in <module> tf.app.run() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run _sys.exit(main(argv)) File "/root/.local/lib/python2.7/site-packages/resnet/resnet_main.py", line 391, in main project=FLAGS.gcp_project) File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/cluster_resolver/python/training/tpu_cluster_resolver.py", line 150, in __init__ self._tpu = compat.as_bytes(tpu) # self._tpu is always bytes File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/compat.py", line 61, in as_bytes (bytes_or_text,)) TypeError: Expected binary or unicode string, got None The replica ps 1 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/resnet/resnet_main.py", line 501, in <module> tf.app.run() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run _sys.exit(main(argv)) File "/root/.local/lib/python2.7/site-packages/resnet/resnet_main.py", line 391, in main project=FLAGS.gcp_project) File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/cluster_resolver/python/training/tpu_cluster_resolver.py", line 150, in __init__ self._tpu = compat.as_bytes(tpu) # self._tpu is always bytes File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/compat.py", line 61, in as_bytes (bytes_or_text,)) TypeError: Expected binary or unicode string, got None The replica ps 2 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/resnet/resnet_main.py", line 501, in <module> tf.app.run() File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run _sys.exit(main(argv)) File "/root/.local/lib/python2.7/site-packages/resnet/resnet_main.py", line 391, in main project=FLAGS.gcp_project) File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/cluster_resolver/python/training/tpu_cluster_resolver.py", line 150, in __init__ self._tpu = compat.as_bytes(tpu) # self._tpu is always bytes File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/compat.py", line 61, in as_bytes (bytes_or_text,)) TypeError: Expected binary or unicode string, got None To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=166660616358&resource=ml_job%2Fjob_id%2Fgpu_20181224_070353&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%22gpu_20181224_070353%22
```

I assume there the 
```
  tpu_cluster_resolver = tf.contrib.cluster_resolver.TPUClusterResolver(
      FLAGS.tpu,
      zone=FLAGS.tpu_zone,
      project=FLAGS.gcp_project)
```
needs to be changed for Nvidia v100. 

However i am not sure what should be the type of resolver for v100.

**Comment by sirtorry** [comment]
@dizcology do you know which resolver needs to be used.
@sreenivasmr can you provide more info on which sample this is?

**Comment by sreenivasmr** [comment]
@sirtorry , @dizcology  it is the below sample

https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/tpu/training/resnet

I have uploaded the complete json log in the below location.

[ml_job_job_id_gpu_20181224_070353__logs__2018-12-24T07-12.json.txt](https://github.com/GoogleCloudPlatform/cloudml-samples/files/2710346/ml_job_job_id_gpu_20181224_070353__logs__2018-12-24T07-12.json.txt)

**Comment by dizcology** [comment]
@sreenivasmr If your goal is only to train a ResNet model on GPU, please consider using this instead: https://github.com/tensorflow/models/tree/master/official/resnet

To submit a training job on CMLE you should specify the `--package-path` as `official.resnet` and `--module-name` as `official.resnet.imagenet_main`, and submit the job from the top level `models` directory.  Please give it a try and let me know if you run into any issues.

**Comment by gogasca** [comment]
@sreenivasmr any updates on this one?

**Comment by sreenivasmr** [comment]
Hi All,
I used the official master and it worked.
ThanksSreeni
    On Tuesday, February 5, 2019, 4:33:34 PM PST, Gonzalo Gasca Meza <notifications@github.com> wrote:  
 
 
@sreenivasmr any updates on this one?

**Comment by gogasca** [comment]
Thanks
