### ISSUE TITLE
Problem running template in the cloud

### ISSUE THREAD

**Issue by Cantstandyabits** [GoogleCloudPlatform/cloudml-samples#382]
### System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow version (use command below): 1.13.1
- Python version: 2.7
- Exact command to reproduce:

gcloud ml-engine jobs submit training template_model_single_20190323_101902 --runtime-version 1.12 --stream-logs --job-dir gs://ben-lstm-test/models/template_model --region us-west1 --scale-tier BASIC_GPU --module-name trainer.task --package-path trainer/

- Tensorflow Transform environment (if applicable, see below):
tensorflow==1.13.1
tensorflow-estimator==1.13.0

### Describe the problem
I have no issues running the census estimator sample on the cloud by executing the 'gcloud' command from my shell on my windows computer, but when I try to run the cloudml-template provided in the cloudml-samples-master (after customizing as required) I receive the following errors after executing the 'gcloud' command indicated above.

```
ERROR   2019-03-23 10:21:55 -0700       master-replica-0                google-cloud-storage 1.6.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.8.2 which is incompatible.
ERROR   2019-03-23 10:21:55 -0700       master-replica-0                google-cloud-firestore 0.28.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.8.2 which is incompatible.
ERROR   2019-03-23 10:21:55 -0700       master-replica-0                google-cloud-spanner 0.29.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.8.2 which is incompatible.
ERROR   2019-03-23 10:21:55 -0700       master-replica-0                google-cloud-resource-manager 0.28.3 has requirement google-cloud-core<0.30dev,>=0.29.0, but you'll have google-cloud-core 0.28.1 which is incompatible.
ERROR   2019-03-23 10:21:55 -0700       master-replica-0                google-api-core 1.8.2 has requirement setuptools>=34.0.0, but you'll have setuptools 20.7.0 which is incompatible.
ERROR   2019-03-23 10:21:55 -0700       master-replica-0                google-cloud-translate 1.3.3 has requirement google-cloud-core<0.30dev,>=0.29.0, but you'll have google-cloud-core 0.28.1 which is incompatible.
ERROR   2019-03-23 10:21:55 -0700       master-replica-0                google-cloud-vision 0.29.0 has requirement google-api-core<0.2.0dev,>=0.1.0, but you'll have google-api-core 1.8.2 which is incompatible.
ERROR   2019-03-23 10:21:55 -0700       master-replica-0                google-cloud-speech 0.30.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.8.2 which is incompatible.
ERROR   2019-03-23 10:21:55 -0700       master-replica-0                google-cloud-runtimeconfig 0.28.3 has requirement google-cloud-core<0.30dev,>=0.29.0, but you'll have google-cloud-core 0.28.1 which is incompatible.
ERROR   2019-03-23 10:21:55 -0700       master-replica-0                google-cloud-logging 1.4.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.8.2 which is incompatible.
ERROR   2019-03-23 10:21:55 -0700       master-replica-0                google-cloud 0.32.0 has requirement google-api-core<0.2.0dev,>=0.1.2, but you'll have google-api-core 1.8.2 which is incompatible.
ERROR   2019-03-23 10:21:55 -0700       master-replica-0                google-cloud 0.32.0 has requirement google-cloud-bigquery<0.29dev,>=0.28.0, but you'll have google-cloud-bigquery 1.6.1 which is incompatible.
ERROR   2019-03-23 10:21:55 -0700       master-replica-0                google-cloud 0.32.0 has requirement google-cloud-bigtable<0.29dev,>=0.28.1, but you'll have google-cloud-bigtable 0.31.1 which is incompatible.
INFO    2019-03-23 10:21:55 -0700       master-replica-0                Installing collected packages: tensorflow, docopt, hdfs, avro, pyarrow, typing, pyvcf, fastavro, pyparsing, pydot, monotonic, fasteners, google-apitools, google-api-core, google-cloud-bigquery, google-cloud-bigtable, google-cloud-pubsub, googledatastore, apache-beam, tensorflow-metadata, tensorflow-transform, wcwidth, prompt-toolkit, decorator, ptyprocess, pexpect, backports.shutil-get-terminal-size, pygments, scandir, pathlib2, ipython-genutils, traitlets, simplegeneric, pickleshare, ipython, MarkupSafe, jinja2, jupyter-core, pyzmq, jupyter-client, Send2Trash, pandocfilters, configparser, entrypoints, defusedxml, testpath, attrs, functools32, pyrsistent, jsonschema, nbformat, webencodings, bleach, mistune, nbconvert, terminado, ipykernel, prometheus-client, ipaddress, notebook, widgetsnbextension, ipywidgets, qtconsole, jupyter-console, jupyter, tensorflow-model-analysis, UNKNOWN
ERROR   2019-03-23 10:21:55 -0700       master-replica-0                google-cloud 0.32.0 has requirement google-cloud-pubsub<0.31dev,>=0.30.0, but you'll have google-cloud-pubsub 0.39.0 which is incompatible.
ERROR   2019-03-23 10:21:55 -0700       master-replica-0                google-cloud-trace 0.17.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.8.2 which is incompatible.
ERROR   2019-03-23 10:21:55 -0700       master-replica-0                google-cloud-error-reporting 0.28.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.8.2 which is incompatible.
ERROR   2019-03-23 10:21:55 -0700       master-replica-0                google-cloud-dns 0.28.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.8.2 which is incompatible.
ERROR   2019-03-23 10:21:55 -0700       master-replica-0                google-cloud-datastore 1.4.0 has requirement google-api-core<0.2.0dev,>=0.1.1, but you'll have google-api-core 1.8.2 which is incompatible.
```
And also an error regarding `feature_column`:

```
ERROR   2019-03-23 10:22:15 -0700       master-replica-0                Traceback (most recent call last):
ERROR   2019-03-23 10:22:15 -0700       master-replica-0                  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
ERROR   2019-03-23 10:22:15 -0700       master-replica-0                    "__main__", fname, loader, pkg_name)
ERROR   2019-03-23 10:22:15 -0700       master-replica-0                  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
ERROR   2019-03-23 10:22:15 -0700       master-replica-0                    exec code in run_globals
ERROR   2019-03-23 10:22:15 -0700       master-replica-0                  File "/root/.local/lib/python2.7/site-packages/trainer/task.py", line 26, in <module>
ERROR   2019-03-23 10:22:15 -0700       master-replica-0                    from trainer import input
ERROR   2019-03-23 10:22:15 -0700       master-replica-0                  File "/root/.local/lib/python2.7/site-packages/trainer/input.py", line 26, in <module>
ERROR   2019-03-23 10:22:15 -0700       master-replica-0                    from trainer import featurizer
ERROR   2019-03-23 10:22:15 -0700       master-replica-0                  File "/root/.local/lib/python2.7/site-packages/trainer/featurizer.py", line 19, in <module>
ERROR   2019-03-23 10:22:15 -0700       master-replica-0                    from tensorflow.feature_column import feature_column
ERROR   2019-03-23 10:22:15 -0700       master-replica-0                ImportError: cannot import name feature_column

```
Full log: [gcloud launch log.txt](https://github.com/GoogleCloudPlatform/cloudml-samples/files/2999645/gcloud.launch.log.txt)

**Comment by Cantstandyabits** [comment]
Follow-up:

Commenting out the following lines in the setup.py file:

```
    'tensorflow==1.12.0',
    'tensorflow-model-analysis==0.11.0'
```

seems to have an effect. The google import errors disappear, but now I get the following error:

```
ERROR   2019-03-23 13:02:05 -0700       master-replica-0                Traceback (most recent call last):
ERROR   2019-03-23 13:02:05 -0700       master-replica-0                  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
ERROR   2019-03-23 13:02:05 -0700       master-replica-0                    "__main__", fname, loader, pkg_name)
ERROR   2019-03-23 13:02:05 -0700       master-replica-0                  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
ERROR   2019-03-23 13:02:05 -0700       master-replica-0                    exec code in run_globals
ERROR   2019-03-23 13:02:05 -0700       master-replica-0                  File "/root/.local/lib/python2.7/site-packages/trainer/task.py", line 23, in <module>
ERROR   2019-03-23 13:02:05 -0700       master-replica-0                    from tensorflow_model_analysis import export as tfma_export
ERROR   2019-03-23 13:02:05 -0700       master-replica-0                ImportError: No module named tensorflow_model_analysis
ERROR   2019-03-23 13:02:06 -0700       master-replica-0                Command '['python', '-m', u'trainer.task', '--job-dir', u'gs://ben-lstm-test/models/template_model']' returned non-zero exit status 1.
INFO    2019-03-23 13:02:06 -0700       master-replica-0                Module completed; cleaning up.
INFO    2019-03-23 13:02:06 -0700       master-replica-0                Clean up finished.
ERROR   2019-03-23 13:02:36 -0700       service         The replica master 0 exited with a non-zero status of 1.
ERROR   2019-03-23 13:02:36 -0700       service         Traceback (most recent call last):
ERROR   2019-03-23 13:02:36 -0700       service           File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
ERROR   2019-03-23 13:02:36 -0700       service             "__main__", fname, loader, pkg_name)
ERROR   2019-03-23 13:02:36 -0700       service           File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
ERROR   2019-03-23 13:02:36 -0700       service             exec code in run_globals
ERROR   2019-03-23 13:02:36 -0700       service           File "/root/.local/lib/python2.7/site-packages/trainer/task.py", line 23, in <module>
ERROR   2019-03-23 13:02:36 -0700       service             from tensorflow_model_analysis import export as tfma_export
ERROR   2019-03-23 13:02:36 -0700       service         ImportError: No module named tensorflow_model_analysis
```

**Comment by Cantstandyabits** [comment]
Follow-up:

I commented out the default required packages in setup.py:

    'tensorflow==1.13.0',
    'tensorflow-model-analysis==0.13.0'

Running again after doing this has the effect of eliminating the numerous google* incompatibility errors witnessed previously, but results in the following new error:

```
ERROR   2019-03-23 14:07:30 -0700       master-replica-0                Traceback (most recent call last):
ERROR   2019-03-23 14:07:30 -0700       master-replica-0                  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
ERROR   2019-03-23 14:07:30 -0700       master-replica-0                    "__main__", fname, loader, pkg_name)
ERROR   2019-03-23 14:07:30 -0700       master-replica-0                  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
ERROR   2019-03-23 14:07:30 -0700       master-replica-0                    exec code in run_globals
ERROR   2019-03-23 14:07:30 -0700       master-replica-0                  File "/root/.local/lib/python2.7/site-packages/trainer/task.py", line 23, in <module>
ERROR   2019-03-23 14:07:30 -0700       master-replica-0                    from tensorflow_model_analysis import export as tfma_export
ERROR   2019-03-23 14:07:30 -0700       master-replica-0                ImportError: No module named tensorflow_model_analysis
```

Why is it unable to find tensorflow_model_analysis? I checked `.local/lib/python2.7/site-packages` in the console in just to be sure, and tensorflow_model_analysis is there.

**Comment by dizcology** [comment]
@Cantstandyabits could you try and run the `gcloud` command with flag `--runtime-version 1.13` with `'tensorflow-model-analysis==0.13.0'` uncommented?

**Comment by ksalama** [comment]
The template is updated now to use TensorFlow version 1.13
I think the issue can be closed
