### ISSUE TITLE
Failed training job for reddit

### ISSUE THREAD

**Issue by danielduckworth** [GoogleCloudPlatform/cloudml-samples#40]
I'm a beginner with Python and Tensorflow.

I ran the pre-processing script without a problem.

I trained the linear model.

However when I train the deep model, it fails. 

Note that I changed:

workerCount: 5
parameterServerCount: 2

Error:
The replica master 0 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/trainer/task.py", line 29, in <module> from tensorflow_transform.saved import input_fn_maker File "/root/.local/lib/python2.7/site-packages/tensorflow_transform/saved/input_fn_maker.py", line 23, in <module> from tensorflow_transform.saved import saved_transform_io File "/root/.local/lib/python2.7/site-packages/tensorflow_transform/saved/saved_transform_io.py", line 26, in <module> from tensorflow_transform.saved import saved_model_loader File "/root/.local/lib/python2.7/site-packages/tensorflow_transform/saved/saved_model_loader.py", line 21, in <module> from tensorflow.python.saved_model import loader_impl ImportError: cannot import name loader_impl The replica worker 0 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/trainer/task.py", line 29, in <module> from tensorflow_transform.saved import input_fn_maker File "/root/.local/lib/python2.7/site-packages/tensorflow_transform/saved/input_fn_maker.py", line 23, in <module> from tensorflow_transform.saved import saved_transform_io File "/root/.local/lib/python2.7/site-packages/tensorflow_transform/saved/saved_transform_io.py", line 26, in <module> from tensorflow_transform.saved import saved_model_loader File "/root/.local/lib/python2.7/site-packages/tensorflow_transform/saved/saved_model_loader.py", line 21, in <module> from tensorflow.python.saved_model import loader_impl ImportError: cannot import name loader_impl The replica worker 1 exited with a non-zero status of 1. Termination reason: Error. Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/root/.local/lib/python2.7/site-packages/trainer/task.py", line 29, in <module> from tensorflow_transform.saved import input_fn_maker File "/root/.local/lib/python2.7/site-packages/tensorflow_transform/saved/input_fn_maker.py", line 23, in <module> from tensorflow_transform.saved import saved_transform_io File "/root/.local/lib/python2.7/site-packages/tensorflow_transform/saved/saved_transform_io.py", line 26, in <module> from tensorflow_transform.saved import saved_model_loader File "/root/.local/lib/python2.7/site-packages/tensorflow_transform/saved/saved_model_loader.py", line 21, in <module> from tensorflow.python.saved_model import loader_impl ImportError: cannot import name loader_impl To find out more about why your job exited please check the logs: https://console.cloud.google.com/logs/viewer?project=283482469300&resource=ml_job%2Fjob_id%2Freddit_comments_deep_daniel_20170417_152317&advancedFilter=resource.type%3D%22ml_job%22%0Aresource.labels.job_id%3D%22reddit_comments_deep_daniel_20170417_152317%22

Training input:

{
  "scaleTier": "CUSTOM",
  "masterType": "complex_model_m",
  "workerType": "complex_model_m",
  "parameterServerType": "complex_model_m",
  "workerCount": "5",
  "parameterServerCount": "2",
  "packageUris": [
    "gs://naturalscore-159511-mlengine/reddit_comments_deep_daniel_20170417_152317/f9641cc367d4b498367f681a16628d6f0f9287e62ad01e9e9ca586fdf690c94d/trainer-1.0.tar.gz"
  ],
  "pythonModule": "trainer.task",
  "args": [
    "--model_type",
    "deep",
    "--hidden_units",
    "1062",
    "1062",
    "1062",
    "1062",
    "1062",
    "1062",
    "1062",
    "1062",
    "1062",
    "1062",
    "1062",
    "--batch_size",
    "512",
    "--eval_steps",
    "250",
    "--output_path",
    "gs://naturalscore-159511-mlengine/daniel/reddit_comments/output/reddit_comments_deep_daniel_20170417_152317",
    "--raw_metadata_path",
    "gs://naturalscore-159511-mlengine/daniel/reddit_comments/preproc/raw_metadata",
    "--transformed_metadata_path",
    "gs://naturalscore-159511-mlengine/daniel/reddit_comments/preproc/transformed_metadata",
    "--transform_savedmodel",
    "gs://naturalscore-159511-mlengine/daniel/reddit_comments/preproc/transform_fn",
    "--eval_data_paths",
    "gs://naturalscore-159511-mlengine/daniel/reddit_comments/preproc/features_eval*",
    "--train_data_paths",
    "gs://naturalscore-159511-mlengine/daniel/reddit_comments/preproc/features_train*"
  ],
  "region": "us-central1"
}

**Comment by elibixby** [comment]
@katsiapis

**Comment by elibixby** [comment]
My suspicion is that you deployed from the wrong directory, and the `setup.py` file was not correctly picked up by `gcloud ml-engine jobs submit training`, and as such the required `tensorflow_transform` dependency was not installed server-side. 

Can you confirm the command you used to deploy?

**Comment by puneith** [comment]
@danielduckworth Closing this because of inactivity and because we know this works. Please feel free to re-open or file new issue if the instructions are not clear somewhere to cause this issue.

**Comment by giksa** [comment]
I have the same problem and I use the next command:
```
gcloud ml-engine jobs submit training `whoami`_object_detection_`date +%s` \                                                                                         
    --runtime-version 1.4 \
    --job-dir=gs://${YOUR_GCS_BUCKET}/train \
    --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz \
    --module-name object_detection.train \
    --region us-central1 \
    --config object_detection/samples/cloud/cloud.yml \
    -- \
    --train_dir=gs://${YOUR_GCS_BUCKET}/train \
    --pipeline_config_path=gs://${YOUR_GCS_BUCKET}/data/faster_rcnn_inception_v2_coco.config

```

**Comment by ssimontacchi** [comment]
same problem:
gcloud ml-engine jobs submit training object_detection_`date +%s` \
    --job-dir=gs://{YOUR_GCS_BUCKET}/train \
    --packages dist/object_detection-0.1.tar.gz,slim/dist/slim-0.1.tar.gz,cocoapi/pycocotools-2.0.tar.gz \
    --module-name object_detection.train \
    --region us-east1 \
    --config cloud.yaml \
    -- \
    --train_dir=gs://{YOUR_GCS_BUCKET}/train \
    --pipeline_config_path=gs://{YOUR_GCS_BUCKET}/data/faster_rcnn_inception_v2_coco.config
