### ISSUE TITLE
Pin dependencies in installation instructions for reddit_tft

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/cloudml-samples#47]
Reading directly from the Bigquery tables
```
$ python preprocess.py --training_data fh-bigquery.reddit_comments.2015_12 \
>                      --eval_data fh-bigquery.reddit_comments.2016_01 \
>                      --predict_data fh-bigquery.reddit_comments.2016_02 \
>                      --output_dir $GCS_PATH/preproc \
>                      --project_id $PROJECT \
>                      --cloud
```
We get the following error.

```
(343abf01bbde6d65): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/batchworker.py", line 544, in do_work
    work_executor.execute()
  File "dataflow_worker/executor.py", line 971, in dataflow_worker.executor.MapTaskExecutor.execute (dataflow_worker/executor.c:30533)
    with op.scoped_metrics_container:
  File "dataflow_worker/executor.py", line 972, in dataflow_worker.executor.MapTaskExecutor.execute (dataflow_worker/executor.c:30481)
    op.start()
  File "dataflow_worker/executor.py", line 499, in dataflow_worker.executor.DoOperation.start (dataflow_worker/executor.c:17992)
    def start(self):
  File "dataflow_worker/executor.py", line 500, in dataflow_worker.executor.DoOperation.start (dataflow_worker/executor.c:17886)
    with self.scoped_start_state:
  File "dataflow_worker/executor.py", line 505, in dataflow_worker.executor.DoOperation.start (dataflow_worker/executor.c:17087)
    pickler.loads(self.spec.serialized_fn))
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/internal/pickler.py", line 212, in loads
    return dill.loads(s)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 277, in loads
    return load(file)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 266, in load
    obj = pik.load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 423, in find_class
    return StockUnpickler.find_class(self, module, name)
  File "/usr/lib/python2.7/pickle.py", line 1126, in find_class
    klass = getattr(mod, name)
AttributeError: 'module' object has no attribute 'flatten_value_to_list'
```

**Comment by elibixby** [comment]
This appears to be an error with dependencies not being pinned to an older `tensorflow-transform` version. The solutions is:

```
pip install --upgrade tensorflow-transform==0.1.7
```

I will submit a `requirements.txt` with all dependencies pinned and update instructions to use that so this doesn't happen again.

**Comment by elmer-garduno** [comment]
tensorflow-transform==0.1.8 fixes this problem, I think

**Comment by elibixby** [comment]
@elmer-garduno bringing your information from the internal thread here: It sounds like there are incompatibilities between the version of apache beam we request installs for on the Dataflow server and the version installed locally. To fix this we'll need to both pin versions client side, and change the versions required in the setup.py for tensorflow-transform? 

Is this a sample issue of a tft issue? 

(FYI using tensorflow-transform==0.1.8 is actually what broke this)

**Comment by elmer-garduno** [comment]
I have pushed an update to the setup files to be 0.1.9. tensorflow-transform is pinned to 0.6.0 for now will be upgraded to 2.0.0 soon. Sorry for the breakage between 0.1.7 and 0.1.8.

**Comment by elibixby** [comment]
Great! Thanks Elmer!
