### ISSUE TITLE
Flowers sample preprocessing fails to run on cloud

### ISSUE THREAD

**Issue by maysamemadi** [GoogleCloudPlatform/cloudml-samples#49]
Running `sample.sh` fails at [preprocessing](https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/flowers/sample.sh#L40).

The issue seems to be with pickling. The traceback ends with: `pickle.PicklingError: Can't pickle <class 'gtk.__main__.GInitiallyUnowned'>: it's not found as gtk.__main__.GInitiallyUnowned`. I have `apache-beam[gcp]==0.6.0` installed and my `dill` version is 0.2.6.

Here's the full Traceback:
```Traceback (most recent call last):
  File "trainer/preprocess.py", line 482, in <module>
    main(sys.argv[1:])
  File "trainer/preprocess.py", line 478, in main
    run(arg_dict)
  File "trainer/preprocess.py", line 386, in run
    configure_pipeline(p, in_args)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/pipeline.py", line 170, in __exit__
    self.run().wait_until_finish()
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/pipeline.py", line 160, in run
    pickler.dump_session(os.path.join(tmpdir, 'main_session.pickle'))
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/internal/pickler.py", line 224, in dump_session
    dill.dump_session(file_path)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 350, in dump_session
    pickler.dump(main)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/internal/pickler.py", line 124, in save_module
    return old_save_module(pickler, obj)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 1197, in save_module
    state=_main_dict)
  File "/usr/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/internal/pickler.py", line 160, in new_save_module_dict
    return old_save_module_dict(pickler, obj)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 841, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 1258, in save_type
    StockPickler.save_global(pickler, obj)
  File "/usr/lib/python2.7/pickle.py", line 754, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <class 'gtk.__main__.GInitiallyUnowned'>: it's not found as gtk.__main__.GInitiallyUnowned```

**Comment by elibixby** [comment]
Yes I suspect this is related to the version incompatibilities we've seen before. See #47 
Let me know if (in a brand new clean virtualenv!!) running `pip install --upgrade tensorflow-tranform==0.1.7` fixes this for you.

**Comment by maysamemadi** [comment]
Thanks for the quick reply and the fix.

I tried `tensorflow-transform` versions 0.1.7, 0.1.8 and 0.1.9 in clean virtualenvs and all three worked. So based on your comment in #47 I'm guessing the fix was on the Dataflow server side.

Thanks for the awesome samples!
