### ISSUE TITLE
Flowers sample pipeline fails, update to Apache Beam

### ISSUE THREAD

**Issue by bw4sz** [GoogleCloudPlatform/cloudml-samples#54]
I've been using the pipeline.py for several weeks without problem. I was gone for a week and it seems that there has been a change. I am now receiving

`(c31f81dff566e4d3): Workflow failed. Causes: (c31f81dff566e6d5): Unable to bring up enough workers: minimum 1, actual 0. Please check your quota and retry later, or please try in a different zone.
`
when calling
```
python pipeline.py \
    --project ${PROJECT} \
    --cloud \
    --train_input_path gs://api-project-773889352370-ml/Hummingbirds/trainingdata.csv \
    --eval_input_path gs://api-project-773889352370-ml/Hummingbirds/testingdata.csv \
    --input_dict gs://api-project-773889352370-ml/Hummingbirds/dict.txt \
    --deploy_model_name "DeepMeerkat" \
    --gcs_bucket ${BUCKET} \
    --output_dir "${GCS_PATH}/" \
    --sample_image_uri  gs://api-project-773889352370-ml/Hummingbirds/Positives/10000.jpg  
```

My repo is here, but its essentially cloned and changed path names

https://github.com/bw4sz/DeepMeerkat/blob/master/training/pipeline.py

I know there have been some changes to python apache beam? Related?

I am running on a cloud compute engine instance, authenticated without issue.

**Comment by bw4sz** [comment]
Just updating, still having trouble with new apache beam.

Troubleshooting
1. pip installed apache-beam --upgrade
2. I grabbed upstream the trainer/preprocess.py and pipeline.py 

Current error is 

`No handlers could be found for logger "oauth2client.contrib.multistore_file"
running sdist
running egg_info
writing requirements to trainer.egg-info/requires.txt
writing trainer.egg-info/PKG-INFO
writing top-level names to trainer.egg-info/top_level.txt
writing dependency_links to trainer.egg-info/dependency_links.txt
reading manifest file 'trainer.egg-info/SOURCES.txt'
writing manifest file 'trainer.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt

running check
warning: check: missing required meta-data: url

creating trainer-0.1
creating trainer-0.1/trainer
creating trainer-0.1/trainer.egg-info
copying files to trainer-0.1...
copying setup.py -> trainer-0.1
copying trainer/__init__.py -> trainer-0.1/trainer
copying trainer/model.py -> trainer-0.1/trainer
copying trainer/preprocess.py -> trainer-0.1/trainer
copying trainer/task.py -> trainer-0.1/trainer
copying trainer/util.py -> trainer-0.1/trainer
copying trainer.egg-info/PKG-INFO -> trainer-0.1/trainer.egg-info
copying trainer.egg-info/SOURCES.txt -> trainer-0.1/trainer.egg-info
copying trainer.egg-info/dependency_links.txt -> trainer-0.1/trainer.egg-info
copying trainer.egg-info/requires.txt -> trainer-0.1/trainer.egg-info
copying trainer.egg-info/top_level.txt -> trainer-0.1/trainer.egg-info
Writing trainer-0.1/setup.cfg
Creating tar archive
removing 'trainer-0.1' (and everything under it)
/usr/local/lib/python2.7/dist-packages/apache_beam/io/gcp/gcsio.py:113: DeprecationWarning: object() takes no parameters
  super(GcsIO, cls).__new__(cls, storage_client))
/usr/local/lib/python2.7/dist-packages/apache_beam/coders/typecoders.py:135: UserWarning: Using fallback coder for typehint: Any.
  warnings.warn('Using fallback coder for typehint: %r.' % typehint)
Traceback (most recent call last):
  File "pipeline.py", line 415, in <module>
    main()
  File "pipeline.py", line 412, in main
    pipeline.run()
  File "pipeline.py", line 381, in run
    train_prefix, eval_prefix = self.preprocess()
  File "pipeline.py", line 198, in preprocess
    _ = [res.get() for res in pipeline_pool]
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
IOError: [Errno 21] Is a directory: '/tmp/tmpw7U3WW/tmpjzmZMO'
`

**Comment by bw4sz** [comment]
Reinstalling everything from scratch seem to do it. Something in there going on.
