### ISSUE TITLE
ImportError: No module named nets

### ISSUE THREAD

**Issue by b01902041** [GoogleCloudPlatform/cloudml-samples#60]
ImportError: No module named nets

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian GNU/Linux 8.8
- **TensorFlow version (use command below)**: 1.2.1
- **Python version**: 2.7
- **Exact command to reproduce**: bash sample.sh
- **Tensorflow Transform environment (if applicable, see below)**: 
tensorflow==1.2.1
apache-beam==2.0.0

To obtain the Tensorflow and Tensorflow Transform environment do

```
pip freeze |grep tensorflow
pip freeze |grep apache-beam
```

### My problem
When I run "sample.sh", I have the error as below.
I set the $PYTHONPATH to 
:/home/claire_chen/models/slim

Does someone know how to fix this problem? Thanks!!

### Error message
```
Traceback (most recent call last):
  File "trainer/preprocess.py", line 492, in <module>
    main(sys.argv[1:])
  File "trainer/preprocess.py", line 488, in main
    run(arg_dict)
  File "trainer/preprocess.py", line 396, in run
    configure_pipeline(p, in_args)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/pipeline.py", line 183, in __exit__
    self.run().wait_until_finish()
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 778, in wait_until_finish
    (self.state, getattr(self._runner, 'last_error_msg', None)), self)
apache_beam.runners.dataflow.dataflow_runner.DataflowRuntimeException: Dataflow pipeline failed. State: FAILED, Error:
(c0a22c82b32c7b96): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/batchworker.py", line 705, in run
    self._load_main_session(self.local_staging_directory)
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/batchworker.py", line 445, in _load_main_session
    pickler.load_session(session_file)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/internal/pickler.py", line 247, in load_session
    return dill.load_session(file_path)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 363, in load_session
    module = unpickler.load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1133, in load_reduce
    value = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 767, in _import_module
    return getattr(__import__(module, None, None, [obj]), obj)
ImportError: No module named nets
```

**Comment by elibixby** [comment]
Can you clarify which sample you are trying to run? It's not clear from your report.
Additionally you generally should not manually manipulate your PYTHONPATH.

**Comment by elibixby** [comment]
Closing due to lack of activity
